#!/usr/bin/env python3
"""
Recover the DrugCLIP authors' TRUE pocket-defining ligand for template-route pockets.

Background
----------
The 339 AI2050 pockets come from two different detection routes (paper p. 12):

  * bare-integer pocket token (e.g. "3")  -> TEMPLATE MATCHING.  A real PDBbind
    ligand was mapped onto the AlphaFold superdomain with TM-align (TM-score > 0.6,
    IoU > 0.6).  The source PDB entry is recorded in the refined-conformation
    filename:  AF-P24941-F1-model_v4_0_3_4_5orz_complex_refined.pdb  ->  5orz.
  * "pocketN" pocket token                -> FPOCKET + GENPACK.  The ligand was
    generated by a diffusion model and is NOT distributed; unrecoverable.

The paper defines a pocket as "the protein residues with at least one heavy atom
within a 6-A radius of the generated ligands".  Our production pockets instead use a
cavity-shaped pseudo-ligand built from fpocket alpha spheres around an averaged Glide
GRID_CENTER.  For the template route that approximation performs at chance
(median pocket AUC 0.507 vs 0.603 for the GenPack route), so this script reconstructs
the real thing.

What it does, per template-route conformation
---------------------------------------------
  1. Parse (uniprot, domain, pocket, conf_idx, pdb_id) from the refined filename.
  2. Fetch <pdb_id> from RCSB into --pdb-cache (cached; reruns are free).
  3. Structurally superpose the RCSB entry onto the AF conformer with PyMOL `cealign`
     (sequence-independent, the closest available analogue to the authors' TM-align).
     The transform applies to the whole mobile object, so its HETATMs move with it.
  4. Pick the pocket ligand: among transposed non-polymer residues, drop solvent /
     ions / cryoprotectants, require >= --min-lig-atoms heavy atoms, and keep the one
     whose centroid is nearest the pocket's averaged GRID_CENTER.
  5. Write <refined-stem-with-dashes>_LIG.pdb = the AF conformer's heavy ATOM records
     plus the transposed ligand as HETATM ... LIG L 1.

Nothing is silently accepted: align RMSD, aligned length, HET code, ligand atom count
and centroid_offset (|ligand centroid - grid centre|) are all written to manifest.csv,
and conformations that fail or look wrong are reported and counted.

The centroid_offset is a result in its own right -- it measures directly whether the
authors' TM-align transposition put the pocket where the grid centre says it is.

Output filenames and pocket_keys are IDENTICAL to prepare_centers_for_drugclip.py and
prepare_fpocket_cavity_for_drugclip.py (underscores in the stem become dashes so the
name has exactly ONE underscore, right before _LIG -- required by encode_pockets.py's
greedy ligand-name regex), so downstream indexes still apply; only geometry changes.

Requires PyMOL:  /home/marina/anaconda3/bin/python

Usage:
    /home/marina/anaconda3/bin/python recover_template_ligands.py \
        --targets-dir /home/marina/Documents/AI2050/Targets/targets \
        --out-base    /home/marina/Documents/AI2050/Targets/targets_ligand \
        --pdb-cache   /home/marina/Documents/AI2050/Targets/pdb_cache
"""

import argparse
import csv
import glob
import os
import re
import sys
import time
import urllib.error
import urllib.request

CENTER_RE = re.compile(r"^(AF-(.+?)-F1-model_v4_(\d+))_(.+)_center\.txt$")
# conf label for a template-route conformation: "<conf_idx>_<pdbid>", e.g. "4_5orz"
TEMPLATE_CONF_RE = re.compile(r"^(\d+)_([0-9a-z]{4})$")

RCSB_PDB = "https://files.rcsb.org/download/{}.pdb"
RCSB_CIF = "https://files.rcsb.org/download/{}.cif"

# Non-ligand HET residues: solvent, ions, buffers, cryoprotectants, sugars, lipids.
# The >= --min-lig-atoms filter removes most of these anyway; this catches the large ones.
JUNK_HET = {
    "HOH", "DOD", "WAT", "SO4", "PO4", "EPE", "MES", "TRS", "GOL", "EDO", "PEG",
    "PG4", "PGE", "1PE", "2PE", "P6G", "MPD", "ACT", "ACY", "FMT", "CIT", "FLC",
    "TLA", "MLA", "SIN", "DMS", "IMD", "BME", "DTT", "TCE", "AZI", "NO3", "CO3",
    "BCT", "SCN", "THJ", "MRD", "BU3", "IPA", "ETX", "OCT", "LDA", "C8E", "BOG",
    "LMT", "DDQ", "PLM", "OLA", "MYR", "STE", "NAG", "NDG", "BMA", "MAN", "GLC",
    "GAL", "FUC", "XYP", "SIA", "UNX", "UNL", "UNK", "ACE", "NH2", "EOH", "MOH",
    # monoatomic ions (belt and braces)
    "NA", "K", "LI", "RB", "CS", "MG", "CA", "SR", "BA", "ZN", "MN", "FE", "FE2",
    "CU", "CU1", "NI", "CO", "CD", "HG", "PT", "AU", "AG", "PB", "CL", "BR", "IOD",
    "F", "XE", "KR", "AR",
}


def read_center(path):
    """Return [x, y, z] floats from a one-line '<x>, <y>, <z>' center file."""
    with open(path) as f:
        parts = [p.strip() for p in f.readline().strip().split(",")]
    if len(parts) != 3:
        return None
    try:
        return [float(p) for p in parts]
    except ValueError:
        return None


def is_hydrogen(line):
    """True if an ATOM/HETATM line is a hydrogen (element cols 77-78, else name heuristic)."""
    element = line[76:78].strip()
    if element:
        return element == "H"
    return line[12:16].strip().lstrip("0123456789").startswith("H")


def heavy_atom_lines(pdb_path):
    """Read a PDB, return its heavy-atom ATOM records only (drop H / non-ATOM)."""
    out = []
    with open(pdb_path) as f:
        for line in f:
            if line.startswith("ATOM") and not is_hydrogen(line):
                out.append(line)
    return out


def last_serial(atom_lines):
    for line in reversed(atom_lines):
        try:
            return int(line[6:11]) + 1
        except ValueError:
            pass
    return 1


def contact_residues(prot_lines, lig_atoms, cutoff=6.0):
    """Count complete residues with a heavy atom within `cutoff` A of the ligand.

    This is upstream's own pocket rule (encode_pockets.py:102), applied here so we never
    write a conformation that would produce an EMPTY pocket. A failed superposition puts the
    transposed ligand off the protein entirely; encode_pockets then calls np.stack on an empty
    list and the whole TARGET dies with

        ValueError: need at least one array to stack

    -- taking every other conformation of that target with it. Observed on 3 of 576
    conformations (O75469 x2, Q9HBH9 x1), all with centroid_offset > 38 A.
    """
    import numpy as _np
    res = {}
    for l in prot_lines:
        res.setdefault((l[21], l[22:27]), []).append(
            (float(l[30:38]), float(l[38:46]), float(l[46:54])))
    L = _np.asarray([(a[1], a[2], a[3]) for a in lig_atoms])
    if not len(L):
        return 0
    n = 0
    for v in res.values():
        if _np.linalg.norm(_np.asarray(v)[:, None, :] - L[None, :, :], axis=-1).min() <= cutoff:
            n += 1
    return n


def hetatm(serial, name, x, y, z, element, resname="LIG", chain="L", resnum=1):
    """Fixed-width HETATM so coords always land at cols 31-54 regardless of name length."""
    return (
        f"HETATM{serial:5d} {name:>4s} {resname:>3s} {chain}{resnum:4d}    "
        f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {element:>2s}  \n"
    )


def fetch_pdb(pdb_id, cache_dir, retries=3, pause=1.0):
    """Download <pdb_id> from RCSB into cache_dir. Returns local path, or None.

    Prefers legacy .pdb; falls back to .cif for entries too large for PDB format.
    """
    os.makedirs(cache_dir, exist_ok=True)
    for ext, url in (("pdb", RCSB_PDB), ("cif", RCSB_CIF)):
        local = os.path.join(cache_dir, f"{pdb_id}.{ext}")
        if os.path.exists(local) and os.path.getsize(local) > 0:
            return local
    for ext, url in (("pdb", RCSB_PDB), ("cif", RCSB_CIF)):
        local = os.path.join(cache_dir, f"{pdb_id}.{ext}")
        for attempt in range(retries):
            try:
                with urllib.request.urlopen(url.format(pdb_id), timeout=60) as r:
                    data = r.read()
                if data:
                    with open(local, "wb") as f:
                        f.write(data)
                    return local
            except urllib.error.HTTPError as e:
                if e.code == 404:
                    break          # not available in this format; try the next one
                time.sleep(pause * (attempt + 1))
            except Exception:
                time.sleep(pause * (attempt + 1))
    return None


def collect_template_confs(target_dir):
    """Yield one record per template-route refined conformation of this target.

    Mirrors prepare_centers_for_drugclip.py's globbing exactly: the pattern is anchored
    on the literal "_<domain>_<pocket>_" so a bare pocket token "2" never matches
    conformation-index 2 of a different pocket.
    """
    refined_dir = os.path.join(target_dir, "refined")
    for cpath in sorted(glob.glob(os.path.join(target_dir, "*_center.txt"))):
        m = CENTER_RE.match(os.path.basename(cpath))
        if not m:
            continue
        prefix, uniprot, domain, pocket = m.group(1), m.group(2), m.group(3), m.group(4)
        if pocket.startswith("pocket"):
            continue               # GenPack route: ligand not distributed, skip
        center = read_center(cpath)
        if center is None:
            continue
        apo = os.path.join(target_dir, f"{prefix}.pdb")
        pattern = os.path.join(refined_dir, f"{prefix}_{pocket}_*_complex_refined.pdb")
        for conf_path in sorted(glob.glob(pattern)):
            stem = os.path.basename(conf_path)[:-len(".pdb")]
            inner = re.match(
                rf"^{re.escape(prefix)}_{re.escape(pocket)}_(.+)_complex_refined$", stem)
            if not inner:
                continue
            conf_label = inner.group(1)
            t = TEMPLATE_CONF_RE.match(conf_label)
            if not t:
                continue           # bare-integer pocket but no PDB id in the filename
            yield {
                "uniprot": uniprot, "domain": domain, "pocket": pocket,
                "conf": conf_label, "conf_idx": t.group(1), "pdb_id": t.group(2),
                "center": center, "conf_path": conf_path, "apo_path": apo,
                "stem": stem, "source_refined_pdb": os.path.basename(conf_path),
            }


def pick_ligand(cmd, obj, center, min_atoms):
    """Return (atoms, resn, offset) for the best pocket ligand in a superposed object.

    atoms is [(name, x, y, z, element), ...] with hydrogens already dropped.  "Best"
    means: not solvent/ion/buffer, at least `min_atoms` heavy atoms, and the centroid
    nearest `center` (the pocket's averaged Glide GRID_CENTER).
    """
    groups = {}
    cmd.iterate_state(
        1, f"{obj} and not polymer and not solvent and not hydro",
        "groups.setdefault((chain, resi, resn), []).append((name, x, y, z, elem))",
        space={"groups": groups},
    )
    best = None
    for (chain, resi, resn), atoms in groups.items():
        if resn.strip().upper() in JUNK_HET or len(atoms) < min_atoms:
            continue
        cx = sum(a[1] for a in atoms) / len(atoms)
        cy = sum(a[2] for a in atoms) / len(atoms)
        cz = sum(a[3] for a in atoms) / len(atoms)
        off = ((cx - center[0]) ** 2 + (cy - center[1]) ** 2 + (cz - center[2]) ** 2) ** 0.5
        if best is None or off < best[2]:
            best = (atoms, resn.strip(), off)
    return best if best else (None, None, None)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--targets-dir", required=True,
                    help="Existing targets tree (read-only): <targets-dir>/<UNIPROT>/")
    ap.add_argument("--out-base", required=True,
                    help="New output tree: <out-base>/<UNIPROT>/pockets/")
    ap.add_argument("--pdb-cache", required=True,
                    help="Directory for downloaded RCSB entries (cached across runs)")
    ap.add_argument("--targets", default="",
                    help="Comma-separated UniProt IDs to restrict to (default: all)")
    ap.add_argument("--min-lig-atoms", type=int, default=10,
                    help="Minimum heavy atoms for a HET group to count as the ligand")
    ap.add_argument("--min-contact-residues", type=int, default=5,
                    help="Reject a conformation whose transposed ligand contacts fewer than "
                         "this many protein residues within 6 A. A failed superposition puts "
                         "the ligand off the protein, and encode_pockets.py then kills the "
                         "whole target with 'need at least one array to stack'.")
    ap.add_argument("--max-offset", type=float, default=5.0,
                    help="Flag a conformation whose ligand centroid is further than this (A) "
                         "from the pocket's grid centre")
    ap.add_argument("--max-align-rmsd", type=float, default=5.0,
                    help="Flag a conformation whose cealign RMSD exceeds this (A)")
    ap.add_argument("--min-align-len", type=int, default=50,
                    help="Flag a conformation with fewer aligned residues than this")
    ap.add_argument("--limit", type=int, default=0,
                    help="Stop after N conformations (smoke test)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Do everything except write _LIG.pdb / manifest.csv")
    args = ap.parse_args()

    try:
        import pymol2
    except ImportError:
        sys.exit("pymol2 not importable - run with /home/marina/anaconda3/bin/python")

    targets_dir = os.path.abspath(args.targets_dir)
    only = {t.strip() for t in args.targets.split(",") if t.strip()}
    target_dirs = sorted(d for d in glob.glob(os.path.join(targets_dir, "*"))
                         if os.path.isdir(d) and (not only or os.path.basename(d) in only))
    if not target_dirs:
        sys.exit(f"no target folders under {targets_dir}")

    records = []
    for td in target_dirs:
        records.extend(collect_template_confs(td))
    if args.limit:
        records = records[:args.limit]

    n_pdb = len({r["pdb_id"] for r in records})
    print(f"{len(records)} template-route conformations across "
          f"{len({r['uniprot'] for r in records})} targets, "
          f"{len({(r['uniprot'], r['domain'], r['pocket']) for r in records})} pockets, "
          f"{n_pdb} distinct RCSB entries")

    by_target = {}
    stats = {"ok": 0, "no_fetch": 0, "no_align": 0, "no_ligand": 0, "flagged": 0,
             "no_contact": 0}
    flags = []

    with pymol2.PyMOL() as p:
        cmd = p.cmd
        cmd.set("retain_order", 1)
        cmd.set("pdb_conect_all", 0)

        for i, r in enumerate(records, 1):
            tag = f"{r['uniprot']} d{r['domain']} p{r['pocket']} c{r['conf']}"
            local = fetch_pdb(r["pdb_id"], args.pdb_cache)
            if not local:
                print(f"  [{i}/{len(records)}] {tag}: FETCH FAILED {r['pdb_id']}")
                stats["no_fetch"] += 1
                continue

            cmd.delete("all")
            try:
                cmd.load(r["conf_path"], "af")
                cmd.load(local, "xtal")
            except Exception as e:
                print(f"  [{i}/{len(records)}] {tag}: LOAD FAILED ({e})")
                stats["no_align"] += 1
                continue

            # cealign(target, mobile): moves `mobile`'s whole object onto `target`,
            # so the crystal ligand travels with its protein into the AF frame.
            try:
                res = cmd.cealign("af and polymer", "xtal and polymer")
                rmsd = float(res.get("RMSD", float("nan")))
                alen = int(res.get("alignment_length", 0))
            except Exception as e:
                print(f"  [{i}/{len(records)}] {tag}: CEALIGN FAILED {r['pdb_id']} ({e})")
                stats["no_align"] += 1
                continue

            atoms, resn, offset = pick_ligand(cmd, "xtal", r["center"], args.min_lig_atoms)
            if not atoms:
                print(f"  [{i}/{len(records)}] {tag}: no ligand >= {args.min_lig_atoms} "
                      f"heavy atoms in {r['pdb_id']}")
                stats["no_ligand"] += 1
                continue

            bad = []
            if offset > args.max_offset:
                bad.append(f"offset={offset:.1f}A")
            if rmsd > args.max_align_rmsd:
                bad.append(f"rmsd={rmsd:.1f}A")
            if alen < args.min_align_len:
                bad.append(f"alen={alen}")
            if bad:
                stats["flagged"] += 1
                flags.append((tag, r["pdb_id"], resn, ",".join(bad)))

            out_stem = r["stem"].replace("_", "-")
            out_name = f"{out_stem}_LIG.pdb"
            prot = heavy_atom_lines(r["conf_path"])
            if not prot:
                print(f"  [{i}/{len(records)}] {tag}: no heavy atoms in refined conf")
                stats["no_ligand"] += 1
                continue

            # Reject rather than flag: an empty pocket kills the whole target at encode time.
            n_contact = contact_residues(prot, atoms)
            if n_contact < args.min_contact_residues:
                print(f"  [{i}/{len(records)}] {tag}: REJECTED - transposed ligand contacts "
                      f"only {n_contact} residues (offset {offset:.1f} A, {r['pdb_id']} {resn}); "
                      f"the superposition failed")
                stats["no_contact"] += 1
                continue

            if not args.dry_run:
                out_dir = os.path.join(args.out_base, r["uniprot"], "pockets")
                os.makedirs(out_dir, exist_ok=True)
                s0 = last_serial(prot)
                with open(os.path.join(out_dir, out_name), "w") as f:
                    f.writelines(prot)
                    for j, (name, x, y, z, elem) in enumerate(atoms):
                        el = (elem or "C").strip() or "C"
                        f.write(hetatm(s0 + j, f"{el}{j + 1}"[:4], x, y, z, el))

            by_target.setdefault(r["uniprot"], []).append({
                "pocket_file": out_name,
                "pocket_key": f"{out_stem}_LIG_L_1",
                "uniprot": r["uniprot"], "domain": r["domain"], "pocket": r["pocket"],
                "conf": r["conf"],
                "center_x": r["center"][0], "center_y": r["center"][1],
                "center_z": r["center"][2],
                "n_lig_atoms": len(atoms), "n_contact_res": n_contact,
                "source_refined_pdb": r["source_refined_pdb"],
                "pdb_id": r["pdb_id"], "het_code": resn,
                "align_rmsd": round(rmsd, 3), "align_len": alen,
                "centroid_offset": round(offset, 3),
                "flag": ";".join(bad),
            })
            stats["ok"] += 1
            if i % 25 == 0 or i == len(records):
                print(f"  [{i}/{len(records)}] ok={stats['ok']} "
                      f"flagged={stats['flagged']} failed="
                      f"{stats['no_fetch'] + stats['no_align'] + stats['no_ligand']}")

    if not args.dry_run:
        for uniprot, rows in by_target.items():
            out_dir = os.path.join(args.out_base, uniprot, "pockets")
            os.makedirs(out_dir, exist_ok=True)
            with open(os.path.join(out_dir, "manifest.csv"), "w", newline="") as f:
                w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
                w.writeheader()
                w.writerows(rows)

    print(f"\n{'[dry-run] ' if args.dry_run else ''}"
          f"wrote {stats['ok']} conformations across {len(by_target)} targets")
    print(f"  failed: fetch={stats['no_fetch']} align={stats['no_align']} "
          f"ligand={stats['no_ligand']} no_contact={stats['no_contact']}")
    print(f"  flagged (written, but check): {stats['flagged']}")
    for tag, pid, resn, why in flags[:40]:
        print(f"    {tag}  {pid} {resn}  {why}")
    if len(flags) > 40:
        print(f"    ... and {len(flags) - 40} more")

    # A high flag or failure rate means the superposition approach is not sound here;
    # per the plan, Phase 4 must not proceed on that basis.
    total = max(1, stats["ok"] + stats["no_fetch"] + stats["no_align"] + stats["no_ligand"])
    bad_frac = (stats["flagged"] + total - stats["ok"]) / total
    print(f"  overall not-clean fraction: {bad_frac:.1%}"
          + ("   <-- investigate before encoding" if bad_frac > 0.2 else "   <-- acceptable"))


if __name__ == "__main__":
    main()
